//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalCare_dbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActivePetTreatments
    {
        public int PetId { get; set; }
        public string PetName { get; set; }
        public string Description { get; set; }
        public string Medicine { get; set; }
        public Nullable<int> Dose { get; set; }
    }
}
