//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalCare_dbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveVisitsForPets
    {
        public int PetId { get; set; }
        public string PetName { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerPhoneNumber { get; set; }
        public System.DateTime VisitDateStart { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
    }
}
